/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PgService } from "../pg.service";
import { PgCreateInput } from "./PgCreateInput";
import { Pg } from "./Pg";
import { PgFindManyArgs } from "./PgFindManyArgs";
import { PgWhereUniqueInput } from "./PgWhereUniqueInput";
import { PgUpdateInput } from "./PgUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

export class PgControllerBase {
  constructor(protected readonly service: PgService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Pg })
  async createPg(@common.Body() data: PgCreateInput): Promise<Pg> {
    return await this.service.createPg({
      data: data,
      select: {
        address: true,
        amenities: true,
        createdAt: true,
        id: true,
        location: true,
        name: true,
        phoneNumber: true,
        price: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Pg] })
  @ApiNestedQuery(PgFindManyArgs)
  async pgs(@common.Req() request: Request): Promise<Pg[]> {
    const args = plainToClass(PgFindManyArgs, request.query);
    return this.service.pgs({
      ...args,
      select: {
        address: true,
        amenities: true,
        createdAt: true,
        id: true,
        location: true,
        name: true,
        phoneNumber: true,
        price: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Pg })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async pg(@common.Param() params: PgWhereUniqueInput): Promise<Pg | null> {
    const result = await this.service.pg({
      where: params,
      select: {
        address: true,
        amenities: true,
        createdAt: true,
        id: true,
        location: true,
        name: true,
        phoneNumber: true,
        price: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Pg })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePg(
    @common.Param() params: PgWhereUniqueInput,
    @common.Body() data: PgUpdateInput
  ): Promise<Pg | null> {
    try {
      return await this.service.updatePg({
        where: params,
        data: data,
        select: {
          address: true,
          amenities: true,
          createdAt: true,
          id: true,
          location: true,
          name: true,
          phoneNumber: true,
          price: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Pg })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePg(
    @common.Param() params: PgWhereUniqueInput
  ): Promise<Pg | null> {
    try {
      return await this.service.deletePg({
        where: params,
        select: {
          address: true,
          amenities: true,
          createdAt: true,
          id: true,
          location: true,
          name: true,
          phoneNumber: true,
          price: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: PgWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        bookingDate: true,
        createdAt: true,
        id: true,

        pg: {
          select: {
            id: true,
          },
        },

        price: true,
        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: PgWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updatePg({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: PgWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updatePg({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: PgWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updatePg({
      where: params,
      data,
      select: { id: true },
    });
  }
}
